#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
a=1
b=0
while [ $b -lt 13 ]
do
    echo "Hour: $b"
    a=1
    while [ $a -le 59 ]
    do
        echo "$a"
        a=$(( a + 1 ))
    done
    b=$(( b + 1 ))
done
