#!/usr/bin/env bash
# Bash script that gives you information about the school file
if [ -e $file ]
then
    echo "school file exists"
    if [ -s $file ]
    then
        echo "school file is empty"
    else
        echo "school file is not empty"
    if [ -f $file]
    then
        echo "school is a regular file"
else
    echo "school file does not exist"
fi
